name: Gerar APK Kotlin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o código do GitHub
        uses: actions/checkout@v4

      - name: Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Validar e corrigir permissões do Gradle
        run: |
          chmod +x gradlew
          sed -i 's/\r$//' gradlew

      - name: Tentar compilar salvando o erro em arquivo
        run: ./gradlew assembleDebug --no-daemon > erro_compilacao.txt 2>&1 || true

      - name: Disponibilizar Relatório de Erro para Download
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-erro
          path: erro_compilacao.txt
